### ISSUE TITLE
Full-text search available

### ISSUE THREAD

**Issue by srid** [TheNeikos/hemera.systems#1]
Heya, I just wanted to let you know that Emanote now has full-text search: https://emanote.srid.ca/guide/search

But since you are overriding the template files, you are not seeing it on your website.

You can review this diff to update your local copy:

https://github.com/EmaApps/emanote/pull/327/files

**Comment by srid** [comment]
Ctrl+K (Cmd+K) already works; it is just the icons that are not visible.

**Comment by TheNeikos** [comment]
! Thank you very much for the heads up
